config/routes.rb
Rails.application.routes.draw do
  root to: 'cinemas#index'
  resources :cinemas, only: [:index, :new, :create, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cinema.rb
class Cinema < ApplicationRecord
  validates :text, presence: true
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController

  def index
    @cinemas = Cinema.all
  end

  def new
    @cinema = Cinema.new
  end

  def create
    Cinema.create(cinema_params)
  end

  def destroy
    cinema = Cinema.find(params[:id])
    cinema.destroy
  end

  def edit
    @cinema = Cinema.find(params[:id])
  end

  def update
    cinema = Cinema.find(params[:id])
    cinema.update(cinema_params)
  end

  private
  def cinema_params
    params.require(:cinema).permit(:name, :image, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/cinemas/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/cinemas/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @cinema, local: true) do |form| %>
      <%= form.text_field :name, placeholder: "Nickname" %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/cinemas/index.html.erb
<div class="contents row">
  <% @cinemas.each do |cinema| %>
    <div class="content_post" style="background-image: url(<%= cinema.image %>);">
    <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
        <li>
            <%= link_to '編集', edit_cinema_path(cinema.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/cinemas/#{cinema.id}", method: :delete %>
          </li>
        </ul>
      </div>
      <p><%= cinema.text %></p>
      <span class="name">
        <%= cinema.name %>
      </span>
    </div>
  <% end %>
</div>

app/views/cinemas/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @cinema, local: true) do |form| %>
      <%= form.text_field :name, placeholder: "Nickname" %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/cinemas/update.html.erb
<div class="contents row">
<div class="success">
<h3>更新が完了しました</h3>
<a class="btn" href"/">投稿一覧に戻る</a>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">CinemaApp</a></h1>
        <div class="user_nav grid-6">
          <a class="post" href="/cinemas/new">投稿する</a>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright CinemaApp 2019.
      </p>
    </footer>
  </body>
</html>